import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul>
            <li>Home</li>
            <li>Services</li>
            <li>About</li>
          </ul>
        </nav>
        <main className="h-screen h-max-[#600px]">{children}</main>
        <footer className="bg-amber-950 text-white text-center">
          Nice Next Js Footer
        </footer>
      </body>
    </html>
  );
}
